rng1:
    build: rng
rng2:
    build: rng
rng3:
    build: rng
rng0:
    image: jpetazzo/hamba
    links:
      - rng1
      - rng2
      - rng3
    command: 80 rng1 80 rng2 80 rng3 80
    ports:
      - "8001:80"

hasher:
    build: hasher
    ports:
      - "8002:80"

webui:
    build: webui
    extra_hosts:
      redis: 52.6.82.68
    ports:
      - "8000:80"

worker:
    build: worker
    extra_hosts:
      redis: 52.6.82.68
    links:
      - rng0:rng
      - hasher
